### ISSUE TITLE
Console cursor is visible after minimizing.

### ISSUE THREAD

**Issue by Dayset** [Dayset/Snake#1]
I will not fix this 😀!
Because I am too lazy for this insignificant issue.

**Comment by upizs** [comment]
Hello, 
I have tried running the game from visual studio with debugger and minimizing, but I cant see the cursor. 
Tried the same with versions from .rar file. 
More specific repro steps would helpful and screenshot as well. 
Thanks.

**Comment by Dayset** [comment]
Hello @upizs 
1. Start the application.
2. Mark lines on the console screen. App will be paused.
3. Minimize and restore application. 
4. Now cursor is visible, despite it was set to CursorVisible = false.

Not really sure if my issues worth fixing.
I am newbie c# and github use too.
Just trying to do things as 'normal' developer would.


https://user-images.githubusercontent.com/17880263/172065961-4834bc87-7212-497c-8f75-7120a1ef5d9a.mp4
