### ISSUE TITLE
C# Console Beeps are distorted when NO music player is running on the PC.

### ISSUE THREAD

**Issue by Dayset** [Dayset/Snake#3]
Beep sounds are severely distorted and not playing as intended if there is no running music/video player application on the PC.
Have been battling with this issue, I thought that something wrong with the code. But it might be on the 'system' side instead.
Maybe this will help to solve the issue https://bytes.com/topic/net/answers/769145-why-console-beep-doent-beep

**Comment by Dayset** [comment]
https://user-images.githubusercontent.com/17880263/172057793-e7554b15-8a52-46e4-98ec-6f7640b0d6f0.mp4

A bits of info. Sounds playing fine on another windows PC. My sound recording device is set to Stereo Mix (to loop system  audio into 'recording mic')

**Comment by upizs** [comment]
@Dayset Found out that Console.Beep() is using the motherboard speaker and therefor might not work on all computers (like mine)
https://bytes.com/topic/net/answers/769145-why-console-beep-doent-beep
It is possible to use a nuget package to play sounds from console as in 
https://www.youtube.com/watch?v=wAYN2BABnG0&ab_channel=MichaelHadley
If you are interested, but that would probably change all the sounds.

**Comment by Dayset** [comment]
@upizs This solution will introduce more complexity than benefits at the project of this level.
I am not a composer and don't have proper .wav files for this specific game, also I like the simplicity and the tones (melody) in it's current state. 
    Issue with PC speaker is not reproduces on  other users PC. Maybe due to reduced windows secondary services. Or Laptop specific model (HP 250 G5) But thanks for the video. Very interesting indeed.

So you don't have sounds in Snake at all?
I have built in speaker, but audio comes from 3.5 jack, generated through Realtek HD audio card.

**Comment by upizs** [comment]
@Dayset No, I don't have any sound. Looked through the setting but can't find anything that would help. 
So I won't be much help with that. Sorry.
