### ISSUE TITLE
Player can choose difficultly before starting game

### ISSUE THREAD

**Issue by upizs** [Dayset/Snake#5]
This could be either before, after, or on the Welcome screen
Could look like this:
Press number for difficulty:
 1. Easy
 2. Normal
 3. Hard
 And then there is a method that listens for the input and has a switch statement that sets the GameSpeedDelay and else just calls the same method again.

**Comment by Dayset** [comment]
Done. Not sure how pretty the solution is from the good coding practice, but it's working.
