### ISSUE TITLE
Refactoring part 1. Screen Operations

### ISSUE THREAD

**Issue by upizs** [Dayset/Snake#7]
Once your code is working then it's time to refactor, tidy up your code, and organize your methods in new relevant classes. 
I propose to create a class ScreenOperations where you can put in the methods related to creating and updating the screen/UI. 
I have already done this and you can have a look and see if you like it or not, This is a pretty simple step forward to clean architecture.

**Comment by Dayset** [comment]
Trying to run it in Full screen mode with 640x480 resolution (available through windows compatibility).
I see the changes but they are crashing console. Map size will be smaller. Can't figure out with the height, it's 'jumping' after GameOver.

**Comment by upizs** [comment]
@Dayset Yeah, if you set the height and width in properties in Console it gets pretty messy. Not sure how to deal with that. I suggest changing the size in screenOperations constructor. 
![image](https://user-images.githubusercontent.com/63521050/172687159-666f29c1-8962-4e63-9d14-6ac1d499effd.png)
That works but with a limit of 160, I think. I changed it to these properties and got a full screen that worked perfectly. 
If you want to change size while in-game, you could add a menu for that. 
If you would like I can tell you how.

**Comment by Dayset** [comment]
No, it's fine with a single preselected option. I will merge and fix screen size issues tomorrow.
